run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - misspell

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/ichbingautam/zephyr-coord

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10

  exclude-rules:
    # Ignore test files
    - path: _test\.go
      linters:
        - all

    # Ignore benchmark files
    - path: _bench_test\.go
      linters:
        - all
